title: data messe learning GitHub Pages
author: data messe
description: > # this means to ignore newlines until "baseurl:"
theme: minima

# social links
twitter_username: data_messe # DO NOT include the @ character, or else the build will fail!
github_username:  datamesse # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
